### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaonie1** [LuckyJayce/ListViewHelper#1]
滑动到最后一页，点击底部view还是会去加载数据，提个小建议，当上啦到底部魏松手的时候，底部view切换内容同时可以在有一个上移跟随的动作

**Comment by tangqifa** [comment]
在类`DeFaultLoadViewFactory.java`的`showNomore()`方法中加入`footView.setOnClickListener(null)`即可解决`当滑动到最后一页，点击底部view还是会去加载数据的问题`

**Comment by LuckyJayce** [comment]
在各个状态添加footView.setOnClickListener的设置。
不需要点击加载更多的状态设置
footView.setOnClickListener(null);
需要点击在家更多的状态设置
footView.setOnClickListener(onClickRefreshListener);
